# Generated by Django 5.1.4 on 2025-03-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_visitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
