from django import forms
class CalculationForm1(forms.Form):
    permeability = forms.CharField(label=r'Проницаемость среды \( k \)', initial=(10**(-13)), widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'number'}))
    fluid_viscosity = forms.CharField(label=r'Вязкость жидкости \( \mu \)', initial=10**(-2), widget=forms.TextInput(attrs={'class': 'form-control'}))
    pressure = forms.CharField(label=r'Давление \(p_0\)', initial=10**(-5), widget=forms.TextInput(attrs={'class': 'form-control'}))
    elastic_capacity_coefficient = forms.CharField(label=r'Коэффициент упругоемкости пласта \( \beta^\circ \)', initial=3 * 10 **(-10), widget=forms.TextInput(attrs={'class': 'form-control'}))
    relaxation_time1 = forms.CharField(label=r'Время релаксации \(\lambda_v\)', initial=1000, widget=forms.TextInput(attrs={'class': 'form-control'}))
    relaxation_time2 = forms.CharField(label=r'Время релаксации \(\lambda_p\)', initial=500, widget=forms.TextInput(attrs={'class': 'form-control'}))
    grid_step_direction1 = forms.CharField(label=r'Шаг сетки по направлению \(\tau\)', initial=10, widget=forms.TextInput(attrs={'class': 'form-control'}))
    grid_step_direction2 = forms.CharField(label=r'Шаг сетки по направлению \(h\)', initial=0.05, widget=forms.TextInput(attrs={'class': 'form-control'}))
    fractional_derivative_time1 = forms.CharField(label=r'Дробная производная по времени \(\alpha\)', initial=0.9, widget=forms.TextInput(attrs={'class': 'form-control'}))
    fractional_derivative_time2 = forms.CharField(label=r'Дробная производная по времени \(\beta\)', initial=0.7, widget=forms.TextInput(attrs={'class': 'form-control'}))
    distance = forms.CharField(label=r'Расстояние \(L\)', initial=40, widget=forms.TextInput(attrs={'class': 'form-control'}))
    maximum_time = forms.CharField(label=r'Максимальное время \(T_{\max}\)', initial=3600, widget=forms.TextInput(attrs={'class': 'form-control'}))

class CalculationForm2(forms.Form):
    permeability = forms.CharField(label=r'Проницаемость среды \( k \)', initial=(10**(-14)), widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'number'}))
    fluid_viscosity = forms.CharField(label=r'Вязкость жидкости \( \mu \)', initial=1.768 * 10**(-3), widget=forms.TextInput(attrs={'class': 'form-control'}))
    pressure = forms.CharField(label=r'Давление \(p_0\)', initial=10**5, widget=forms.TextInput(attrs={'class': 'form-control'}))
    elastic_capacity_coefficient = forms.CharField(label=r'Коэффициент упругоемкости пласта \( \beta^\circ \)', initial=3 * 10**(-8), widget=forms.TextInput(attrs={'class': 'form-control'}))
    relaxation_time1 = forms.CharField(label=r'Время релаксации \(\lambda_v\)', initial=1000, widget=forms.TextInput(attrs={'class': 'form-control'}))
    relaxation_time2 = forms.CharField(label=r'Время релаксации \(\lambda_p\)', initial=500, widget=forms.TextInput(attrs={'class': 'form-control'}))
    grid_step_direction1 = forms.CharField(label=r'Шаг сетки по направлению \(\tau\)', initial=10, widget=forms.TextInput(attrs={'class': 'form-control'}))
    grid_step_direction2 = forms.CharField(label=r'Шаг сетки по направлению \(h\)', initial=0.05, widget=forms.TextInput(attrs={'class': 'form-control'}))
    fractional_derivative_time1 = forms.CharField(label=r'Дробная производная по времени \(\alpha\)', initial=0.9, widget=forms.TextInput(attrs={'class': 'form-control'}))
    fractional_derivative_time2 = forms.CharField(label=r'Дробная производная по времени \(\beta\)', initial=0.7, widget=forms.TextInput(attrs={'class': 'form-control'}))
    distance = forms.CharField(label=r'Расстояние \(L\)', initial=5, widget=forms.TextInput(attrs={'class': 'form-control'}))
    maximum_time = forms.CharField(label=r'Максимальное время \(T_{\max}\)', initial=3600, widget=forms.TextInput(attrs={'class': 'form-control'}))
    gradient_pressure_limit = forms.CharField(label=r'Предельный градиент давления (ПГД) \(g_0 \)', initial=10**5, widget=forms.TextInput(attrs={'class': 'form-control'}))

class CalculationForm3(forms.Form):
    permeability = forms.CharField(label=r'Проницаемость \( k \)', initial=(10**(-13)), widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'number'}))
    fluid_viscosity = forms.CharField(label=r'Вязкость жидкости \( \mu \)', initial=1 * 10**(-2), widget=forms.TextInput(attrs={'class': 'form-control'}))
    initial_pressure = forms.CharField(label=r'Первоначальное давление \(p_k\)', initial=200 * 10**5, widget=forms.TextInput(attrs={'class': 'form-control'}))
    constant_pressure = forms.CharField(label=r'Постоянное давление \(p_c\)', initial=150 * 10**5, widget=forms.TextInput(attrs={'class': 'form-control'}))
    elastic_capacity_coefficient = forms.CharField(label=r'Коэффициент упругоемкости \( \beta^\circ \)', initial=3 * 10**(-10), widget=forms.TextInput(attrs={'class': 'form-control'}))
    relaxation_time1 = forms.CharField(label=r'Время релаксации \(\lambda_v\)', initial=1000, widget=forms.TextInput(attrs={'class': 'form-control'}))
    relaxation_time2 = forms.CharField(label=r'Время релаксации \(\lambda_p\)', initial=500, widget=forms.TextInput(attrs={'class': 'form-control'}))
    grid_step_direction1 = forms.CharField(label=r'Шаг сетки по направлению \(\tau\)', initial=10, widget=forms.TextInput(attrs={'class': 'form-control'}))
    grid_step_direction2 = forms.CharField(label=r'Шаг сетки по направлению \(h\)', initial=0.05, widget=forms.TextInput(attrs={'class': 'form-control'}))
    fractional_derivative_time1 = forms.CharField(label=r'Дробная производная по времени \(\alpha\)', initial=0.9, widget=forms.TextInput(attrs={'class': 'form-control'}))
    fractional_derivative_time2 = forms.CharField(label=r'Дробная производная по времени \(\beta\)', initial=0.7, widget=forms.TextInput(attrs={'class': 'form-control'}))
    distance = forms.CharField(label=r'Расстояние \(L\)', initial=40, widget=forms.TextInput(attrs={'class': 'form-control'}))
    maximum_time = forms.CharField(label=r'Максимальное время \(T_{\max}\)', initial=3600, widget=forms.TextInput(attrs={'class': 'form-control'}))
    gradient_pressure_limit = forms.CharField(label=r'Предельный градиент давления (ПГД) \(r_c \)', initial=0.1, widget=forms.TextInput(attrs={'class': 'form-control'}))
